// ── Canvas atmosphere CSS variable presets ──

import type { CanvasAtmosphere, CssVarMap } from "./types";

export const CANVAS_ATMOSPHERE_VARS: Record<CanvasAtmosphere, CssVarMap> = {
  plain: {
    "canvas-top": "var(--background)",
    "canvas-bottom": "color-mix(in oklch, var(--background) 94%, black)",
    "canvas-glow-1": "transparent",
    "canvas-glow-2": "transparent",
    "canvas-glow-3": "transparent",
    "canvas-mesh": "none",
    "canvas-mesh-opacity": "0",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 22%, transparent)",
    "canvas-grid-opacity": "0.065",
    "canvas-vignette": "radial-gradient(circle at center, transparent 45%, color-mix(in oklch, black 14%, transparent) 100%)",
    "canvas-blur": "0px",
  },
  studio: {
    "canvas-top": "color-mix(in oklch, var(--background) 90%, var(--card))",
    "canvas-bottom": "color-mix(in oklch, var(--background) 84%, black 16%)",
    "canvas-glow-1": "color-mix(in oklch, var(--primary) 16%, transparent)",
    "canvas-glow-2": "color-mix(in oklch, var(--accent) 26%, transparent)",
    "canvas-glow-3": "color-mix(in oklch, var(--sidebar-primary) 14%, transparent)",
    "canvas-mesh": "radial-gradient(circle at 18% 18%, color-mix(in oklch, var(--primary) 18%, transparent) 0%, transparent 42%), radial-gradient(circle at 84% 16%, color-mix(in oklch, var(--accent) 22%, transparent) 0%, transparent 38%), radial-gradient(circle at 55% 100%, color-mix(in oklch, var(--sidebar-primary) 14%, transparent) 0%, transparent 54%)",
    "canvas-mesh-opacity": "0.9",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 18%, transparent)",
    "canvas-grid-opacity": "0.08",
    "canvas-vignette": "radial-gradient(circle at center, transparent 38%, color-mix(in oklch, black 20%, transparent) 100%)",
    "canvas-blur": "120px",
  },
  aurora: {
    "canvas-top": "color-mix(in oklch, var(--background) 82%, var(--card))",
    "canvas-bottom": "color-mix(in oklch, var(--background) 72%, black 28%)",
    "canvas-glow-1": "color-mix(in oklch, var(--primary) 28%, transparent)",
    "canvas-glow-2": "color-mix(in oklch, var(--sidebar-primary) 24%, transparent)",
    "canvas-glow-3": "color-mix(in oklch, var(--accent) 18%, transparent)",
    "canvas-mesh": "radial-gradient(circle at 12% 12%, color-mix(in oklch, var(--primary) 26%, transparent) 0%, transparent 35%), radial-gradient(circle at 86% 14%, color-mix(in oklch, var(--sidebar-primary) 24%, transparent) 0%, transparent 34%), radial-gradient(circle at 48% 102%, color-mix(in oklch, var(--accent) 20%, transparent) 0%, transparent 52%)",
    "canvas-mesh-opacity": "1",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 24%, transparent)",
    "canvas-grid-opacity": "0.09",
    "canvas-vignette": "radial-gradient(circle at center, transparent 34%, color-mix(in oklch, black 24%, transparent) 100%)",
    "canvas-blur": "145px",
  },
  mist: {
    "canvas-top": "color-mix(in oklch, var(--background) 94%, white 6%)",
    "canvas-bottom": "color-mix(in oklch, var(--background) 86%, var(--card) 14%)",
    "canvas-glow-1": "color-mix(in oklch, var(--accent) 20%, transparent)",
    "canvas-glow-2": "color-mix(in oklch, var(--primary) 12%, transparent)",
    "canvas-glow-3": "color-mix(in oklch, white 12%, transparent)",
    "canvas-mesh": "radial-gradient(circle at 20% 16%, color-mix(in oklch, var(--accent) 22%, transparent) 0%, transparent 42%), radial-gradient(circle at 82% 20%, color-mix(in oklch, white 16%, transparent) 0%, transparent 38%), radial-gradient(circle at 50% 100%, color-mix(in oklch, var(--primary) 12%, transparent) 0%, transparent 56%)",
    "canvas-mesh-opacity": "0.72",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 14%, transparent)",
    "canvas-grid-opacity": "0.055",
    "canvas-vignette": "radial-gradient(circle at center, transparent 44%, color-mix(in oklch, black 12%, transparent) 100%)",
    "canvas-blur": "160px",
  },
  nocturne: {
    "canvas-top": "color-mix(in oklch, var(--background) 84%, black 16%)",
    "canvas-bottom": "color-mix(in oklch, var(--background) 64%, black 36%)",
    "canvas-glow-1": "color-mix(in oklch, var(--primary) 16%, transparent)",
    "canvas-glow-2": "color-mix(in oklch, var(--accent) 18%, transparent)",
    "canvas-glow-3": "color-mix(in oklch, black 24%, transparent)",
    "canvas-mesh": "radial-gradient(circle at 16% 18%, color-mix(in oklch, var(--primary) 14%, transparent) 0%, transparent 34%), radial-gradient(circle at 84% 22%, color-mix(in oklch, var(--accent) 16%, transparent) 0%, transparent 32%), radial-gradient(circle at 50% 105%, color-mix(in oklch, var(--sidebar-primary) 12%, transparent) 0%, transparent 48%)",
    "canvas-mesh-opacity": "0.74",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 20%, transparent)",
    "canvas-grid-opacity": "0.085",
    "canvas-vignette": "radial-gradient(circle at center, transparent 30%, color-mix(in oklch, black 32%, transparent) 100%)",
    "canvas-blur": "150px",
  },
};
