// ── Canvas atmosphere CSS variable presets ──

import type { CanvasAtmosphere, CssVarMap } from "./types";

export const CANVAS_ATMOSPHERE_VARS: Record<CanvasAtmosphere, CssVarMap> = {
  workbench: {
    "canvas-top": "color-mix(in oklch, var(--background) 88%, var(--card) 12%)",
    "canvas-bottom": "color-mix(in oklch, var(--background) 78%, black 22%)",
    "canvas-glow-1": "transparent",
    "canvas-glow-2": "transparent",
    "canvas-glow-3": "transparent",
    "canvas-mesh": "none",
    "canvas-mesh-opacity": "0",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 26%, transparent)",
    "canvas-grid-opacity": "0.108",
    "canvas-vignette": "radial-gradient(circle at center, transparent 42%, color-mix(in oklch, black 18%, transparent) 100%)",
    "canvas-blur": "0px",
  },
  blueprint: {
    "canvas-top": "color-mix(in oklch, var(--background) 84%, var(--card) 16%)",
    "canvas-bottom": "color-mix(in oklch, var(--background) 76%, black 24%)",
    "canvas-glow-1": "transparent",
    "canvas-glow-2": "transparent",
    "canvas-glow-3": "transparent",
    "canvas-mesh": "linear-gradient(color-mix(in oklch, var(--foreground) 13%, transparent) 1px, transparent 1px) 0 0 / 64px 64px, linear-gradient(90deg, color-mix(in oklch, var(--foreground) 13%, transparent) 1px, transparent 1px) 0 0 / 64px 64px, linear-gradient(color-mix(in oklch, var(--sidebar-primary) 11%, transparent) 1px, transparent 1px) 0 0 / 16px 16px, linear-gradient(90deg, color-mix(in oklch, var(--sidebar-primary) 11%, transparent) 1px, transparent 1px) 0 0 / 16px 16px",
    "canvas-mesh-opacity": "0.34",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 18%, transparent)",
    "canvas-grid-opacity": "0.048",
    "canvas-vignette": "radial-gradient(circle at center, transparent 40%, color-mix(in oklch, black 20%, transparent) 100%)",
    "canvas-blur": "0px",
  },
  draft: {
    "canvas-top": "color-mix(in oklch, var(--background) 86%, var(--card) 14%)",
    "canvas-bottom": "color-mix(in oklch, var(--background) 82%, black 18%)",
    "canvas-glow-1": "transparent",
    "canvas-glow-2": "transparent",
    "canvas-glow-3": "transparent",
    "canvas-mesh": "radial-gradient(circle, color-mix(in oklch, var(--foreground) 12%, transparent) 0 0.85px, transparent 1px) 0 0 / 32px 32px, radial-gradient(circle, color-mix(in oklch, var(--sidebar-primary) 10%, transparent) 0 0.75px, transparent 1px) 16px 16px / 32px 32px",
    "canvas-mesh-opacity": "0.34",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 18%, transparent)",
    "canvas-grid-opacity": "0.044",
    "canvas-vignette": "radial-gradient(circle at center, transparent 46%, color-mix(in oklch, black 15%, transparent) 100%)",
    "canvas-blur": "0px",
  },
  signal: {
    "canvas-top": "color-mix(in oklch, var(--background) 78%, black 22%)",
    "canvas-bottom": "color-mix(in oklch, var(--background) 66%, black 34%)",
    "canvas-glow-1": "transparent",
    "canvas-glow-2": "transparent",
    "canvas-glow-3": "transparent",
    "canvas-mesh": "radial-gradient(circle, color-mix(in oklch, var(--foreground) 10%, transparent) 0 0.8px, transparent 1px) 0 0 / 28px 28px, linear-gradient(color-mix(in oklch, var(--sidebar-primary) 12%, transparent) 1px, transparent 1px) 0 0 / 144px 144px, linear-gradient(90deg, color-mix(in oklch, var(--sidebar-primary) 12%, transparent) 1px, transparent 1px) 0 0 / 144px 144px",
    "canvas-mesh-opacity": "0.32",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 18%, transparent)",
    "canvas-grid-opacity": "0.046",
    "canvas-vignette": "radial-gradient(circle at center, transparent 34%, color-mix(in oklch, black 30%, transparent) 100%)",
    "canvas-blur": "0px",
  },
};
