// ── Canvas atmosphere CSS variable presets ──

import type { CanvasAtmosphere, CssVarMap } from "./types";

export const CANVAS_ATMOSPHERE_VARS: Record<CanvasAtmosphere, CssVarMap> = {
  workbench: {
    "canvas-top": "color-mix(in oklch, var(--background) 88%, var(--card) 12%)",
    "canvas-bottom": "color-mix(in oklch, var(--background) 78%, black 22%)",
    "canvas-glow-1": "transparent",
    "canvas-glow-2": "transparent",
    "canvas-glow-3": "transparent",
    "canvas-mesh": "none",
    "canvas-mesh-opacity": "0",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 18%, transparent)",
    "canvas-grid-opacity": "0.06",
    "canvas-vignette": "radial-gradient(circle at center, transparent 42%, color-mix(in oklch, black 18%, transparent) 100%)",
    "canvas-blur": "0px",
  },
  blueprint: {
    "canvas-top": "color-mix(in oklch, var(--background) 84%, var(--card) 16%)",
    "canvas-bottom": "color-mix(in oklch, var(--background) 76%, black 24%)",
    "canvas-glow-1": "transparent",
    "canvas-glow-2": "transparent",
    "canvas-glow-3": "transparent",
    "canvas-mesh": "linear-gradient(color-mix(in oklch, var(--foreground) 8%, transparent) 1px, transparent 1px) 0 0 / 64px 64px, linear-gradient(90deg, color-mix(in oklch, var(--foreground) 8%, transparent) 1px, transparent 1px) 0 0 / 64px 64px, linear-gradient(color-mix(in oklch, var(--sidebar-primary) 10%, transparent) 1px, transparent 1px) 0 0 / 16px 16px, linear-gradient(90deg, color-mix(in oklch, var(--sidebar-primary) 10%, transparent) 1px, transparent 1px) 0 0 / 16px 16px",
    "canvas-mesh-opacity": "0.48",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 18%, transparent)",
    "canvas-grid-opacity": "0.052",
    "canvas-vignette": "radial-gradient(circle at center, transparent 40%, color-mix(in oklch, black 20%, transparent) 100%)",
    "canvas-blur": "0px",
  },
  draft: {
    "canvas-top": "color-mix(in oklch, var(--background) 86%, var(--card) 14%)",
    "canvas-bottom": "color-mix(in oklch, var(--background) 82%, black 18%)",
    "canvas-glow-1": "transparent",
    "canvas-glow-2": "transparent",
    "canvas-glow-3": "transparent",
    "canvas-mesh": "linear-gradient(color-mix(in oklch, var(--foreground) 7%, transparent) 1px, transparent 1px) 0 0 / 100% 28px, linear-gradient(112deg, transparent 0 49%, color-mix(in oklch, var(--foreground) 5%, transparent) 49.5% 50.5%, transparent 51%) 0 0 / 96px 96px",
    "canvas-mesh-opacity": "0.56",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 16%, transparent)",
    "canvas-grid-opacity": "0.045",
    "canvas-vignette": "radial-gradient(circle at center, transparent 46%, color-mix(in oklch, black 15%, transparent) 100%)",
    "canvas-blur": "0px",
  },
  signal: {
    "canvas-top": "color-mix(in oklch, var(--background) 78%, black 22%)",
    "canvas-bottom": "color-mix(in oklch, var(--background) 66%, black 34%)",
    "canvas-glow-1": "transparent",
    "canvas-glow-2": "transparent",
    "canvas-glow-3": "transparent",
    "canvas-mesh": "repeating-linear-gradient(0deg, color-mix(in oklch, var(--foreground) 5%, transparent) 0 1px, transparent 1px 5px), repeating-linear-gradient(90deg, transparent 0 31px, color-mix(in oklch, var(--sidebar-primary) 9%, transparent) 31px 32px, transparent 32px 96px)",
    "canvas-mesh-opacity": "0.5",
    "canvas-grid-color": "color-mix(in oklch, var(--foreground) 18%, transparent)",
    "canvas-grid-opacity": "0.05",
    "canvas-vignette": "radial-gradient(circle at center, transparent 34%, color-mix(in oklch, black 30%, transparent) 100%)",
    "canvas-blur": "0px",
  },
};
